version: 2.1
jobs:
  build:
    docker:
      - image: mattrayner/lamp:latest-1804     
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Install Docker client"         
          command: |
            apt-get update
            apt-get install -y docker.io
      - run:
          name: "Build and push docker image"
          command: |
            echo "FROM ubuntu:16.04" > Dockerfile
            docker build -t imagetest:1.0 .
            docker images
            docker tag imagetest:1.0 srolla/docker_seb
            echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
            docker push srolla/docker_seb