version: 2.1
jobs:
  build:
    docker:
      - image: mattrayner/lamp:latest-1804
        
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            apt-get update
            apt-get install docker-ce
